# Generated by Django 5.2.3 on 2025-07-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
